### ISSUE TITLE
🐛[BUG] 在hosts文件原先有了其他的映射地址后可能无法写入在其他映射地址

### ISSUE THREAD

**Issue by GodLikesYou** [SteamTools-Team/SteamTools#180]
### 🐛 描述(Description)

在hosts文件中有了之前的其他映射地址,从而导致steam++无法写入hosts的代理映射地址.
### 📷 复现步骤(Steps to Reproduce)

1. 开启steam++ 的hosts代理模式后,steam社区无效果.
2. 打开hosts文件发现文件内的映射地址没有被写入.
3. 查看log日志发现是hosts原先存在的映射地址从而导致无法写入steam++的映射地址.

### 📄 [异常/日志]信息([Exception/Log] Information)
2021-05-01 11:20:41.4239|Error|HostsFileS|UpdateHosts catch. | System.Exception: hosts file line 34 duplicate
   at System.Application.Services.Implementation.HostsFileServiceImpl.HandleLine(Int32 line_num, HashSet`1 domains, String line_value, String[]& line_split_array, Func`2 func)
   at System.Application.Services.Implementation.HostsFileServiceImpl.HandleHosts(Boolean isUpdateOrRemove, IReadOnlyDictionary`2 hosts)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.0.0.6β版本
- 系统版本号(OS Version): Windows 10 20H2

**Comment by AigioL** [comment]
已在 https://github.com/SteamTools-Team/SteamTools/commit/b19b5cf88fb4d3683e3bcbdc5c0c63747f269843 中修复，请更新至 2.0.0.8
