### ISSUE TITLE
🐛[BUG] Windows系统代理方式反代存在问题

### ISSUE THREAD

**Issue by wsvg14** [SteamTools-Team/SteamTools#182]
### 🐛 描述(Description)

在使用WIndows系统代理模式时，访问steam社区会显示ERR_EMPTY_RESPONSE
（有可能会导致重启后无法上网）
使用hosts方式正常

### 📷 复现步骤(Steps to Reproduce)

1. 安装证书并且启动Windows系统代理模式
2. Edge访问steam社区
3. 提示ERR_EMPTY_RESPONSE

### 📄 [异常/日志]信息([Exception/Log] Information)
2021-05-01 19:34:28.5867|Error|Proxy|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request
 ---> System.IO.IOException: net_io_eof
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, List`1 applicationProtocols, Boolean isConnect, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.GetServerConnection(ProxyServer proxyServer, SessionEventArgsBase session, Boolean isConnect, List`1 applicationProtocols, Boolean noCache, Boolean prefetch, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.Release(Task`1 connectionCreateTask, Boolean closeServerConnection)
   Exception_EndOfInnerExceptionStack
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleClient(ExplicitProxyEndPoint endPoint, TcpClientConnection clientConnection)
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.0
- 系统版本号(OS Version): Windows 10.19042.928

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/2156103/116781277-79d88400-aab4-11eb-9b0d-1760387b9858.png)

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
