### ISSUE TITLE
🐛[BUG] 因别的加速器以及VPN异常闪退

### ISSUE THREAD

**Issue by baiuu** [SteamTools-Team/SteamTools#207]
### 🐛 描述(Description)

开启其他加速器例如腾讯加速器、Temo加速器、v2rayN 会导致STEAM++异常闪退。

### 📷 复现步骤(Steps to Reproduce)

打开STEAM++
打开加速器并启用 一段时间后

### 📄 [异常/日志]信息([Exception/Log] Information)
日志里无记录

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.0.0.8
- 系统版本号(OS Version):  Windows 10.19042.928
-

**Comment by baiuu** [comment]
这个复现难度有点大。。不是必触发

**Comment by rmbadmin** [comment]
logs文件夹没有对应的日志吗？
那windows日志里应用程序日志是否有相关信息日志

**Comment by baiuu** [comment]
> logs文件夹没有对应的日志吗？
> 那windows日志里应用程序日志是否有相关信息日志

有日志是没有闪退的记录我看看windows日志
错误应用程序名称: Steam++.exe，版本: 2.0.0.8，时间戳: 0x6065ee3b
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.906，时间戳: 0x26452a2a
异常代码: 0xe0434352
错误偏移量: 0x0012a6e2
错误进程 ID: 0x3a80
错误应用程序启动时间: 0x01d740931b9bd68a
错误应用程序路径: C:\Program Files (x86)\Steam++\Steam++.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: c9c2d165-f484-4ca6-9387-ad59a5c51a3e
错误程序包全名: 
错误程序包相对应用程序 ID: 
曾经有过
有这样的内容

**Comment by baiuu** [comment]
> logs文件夹没有对应的日志吗？
> 那windows日志里应用程序日志是否有相关信息日志

今天打开腾讯加速器崩了


日志有已下内容
2021-05-09 19:19:36.3438|Error|Proxy|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'discord.com' with certificate 'discord.com'.
 ---> System.Security.Authentication.AuthenticationException: net_auth_SSPI
 ---> System.ComponentModel.Win32Exception (0x80090331): 因为算法不同，客户端和服务器无法通信。
   Exception_EndOfInnerExceptionStack
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)

**Comment by baiuu** [comment]
2.2.0版本暂未出现该问题
