### ISSUE TITLE
放在后台会自动退出。。。而且在库存页面还是闪退

### ISSUE THREAD

**Issue by FrzenMonarch** [SteamTools-Team/SteamTools#208]
[Logs.zip](https://github.com/SteamTools-Team/SteamTools/files/6421946/Logs.zip)

**Comment by AigioL** [comment]
@rmbadmin 

Image2 引发了 空指针异常
```
2021-05-02 21:05:49.7154|Error|Main|Stopped program because of exception, name: Main, isTerminating:  | System.NullReferenceException: Arg_NullReferenceException
   at Avalonia.Skia.ImmutableBitmap..ctor(Stream stream, Int32 decodeSize, Boolean horizontal, BitmapInterpolationMode interpolationMode) in /_/src/Skia/Avalonia.Skia/ImmutableBitmap.cs:line 62
   at Avalonia.Skia.PlatformRenderInterface.LoadBitmapToWidth(Stream stream, Int32 width, BitmapInterpolationMode interpolationMode) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 89
   at Avalonia.Media.Imaging.Bitmap.DecodeToWidth(Stream stream, Int32 width, BitmapInterpolationMode interpolationMode) in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 24
   at AvaloniaGif.Image2.<SourceChanged>g__DecodeImage|44_0(Stream stream, <>c__DisplayClass44_0& )
   at AvaloniaGif.Image2.SourceChanged(AvaloniaPropertyChangedEventArgs e)
```

API 的 SSL 证书验证失败，很奇怪
```
2021-05-03 14:20:20.8285|Error|CloudServiceClient|ApiConn Fail(1006)，Url：api/Accelerate/All | System.Net.Http.HttpRequestException: net_http_ssl_connection_failed
 ---> System.Security.Authentication.AuthenticationException: net_ssl_io_cert_validation, RemoteCertificateNameMismatch, RemoteCertificateChainErrors
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
```

DNS 解析问题？这个错误重复次数巨多
```
2021-05-03 23:30:53.6190|Error|Proxy|ProxyServer ExceptionFunc | System.Exception: Exception thrown in user event
 ---> System.Net.Sockets.SocketException (11001): 不知道这样的主机。
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped)
Exception_EndStackTraceFromPreviousThrow
   at System.Application.Services.Implementation.HttpProxyServiceImpl.OnRequest(Object sender, SessionEventArgs e)
   at Titanium.Web.Proxy.Extensions.FuncExtensions.internalInvokeAsync[T](AsyncEventHandler`1 callback, Object sender, T args, ExceptionHandler exceptionFunc)
   Exception_EndOfInnerExceptionStack
```

代理域名的证书与源网站证书算法不一致？
```
2021-05-04 07:58:37.4060|Error|Proxy|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'discord.com' with certificate 'discord.com'.
 ---> System.Security.Authentication.AuthenticationException: net_auth_SSPI
 ---> System.ComponentModel.Win32Exception (0x80090331): 因为算法不同，客户端和服务器无法通信。
   Exception_EndOfInnerExceptionStack
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
```

OOM
```
2021-05-04 15:04:24.9837|Error|SteamConnectService|Task LongRunning | System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
```

App.Shutdown 没在主线程中执行
```
2021-05-04 15:04:25.4429|Error|Main|(App)Close exception when exception occurs | System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 701
   at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 523
   at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 491
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 88
   at System.Application.UI.App.Shutdown(Int32 exitCode)
   at System.Application.UI.Program.<Main>g__HandleGlobalException|6_5(Exception ex, String name, Nullable`1 isTerminating)
2021-05-04 15:04:25.6160|Error|Main|Stopped program because of exception, name: UnhandledException, isTerminating: True | System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2021-05-04 15:04:25.6308|Error|Main|(App)Close exception when exception occurs | System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 701
   at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 523
   at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 491
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 88
   at System.Application.UI.App.Shutdown(Int32 exitCode)
   at System.Application.UI.Program.<Main>g__HandleGlobalException|6_5(Exception ex, String name, Nullable`1 isTerminating)
2021-05-04 15:04:25.7245|Error|Main|Stopped program because of exception, name: UnhandledException, isTerminating: True | System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2021-05-04 15:04:25.7245|Error|Main|(App)Close exception when exception occurs | System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 701
   at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 523
   at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 491
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 88
   at System.Application.UI.App.Shutdown(Int32 exitCode)
   at System.Application.UI.Program.<Main>g__HandleGlobalException|6_5(Exception ex, String name, Nullable`1 isTerminating)
2021-05-04 15:04:25.8499|Error|Main|Stopped program because of exception, name: UnhandledException, isTerminating: True | System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
2021-05-04 15:04:25.8654|Error|Main|(App)Close exception when exception occurs | System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 701
   at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 523
   at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 491
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 88
   at System.Application.UI.App.Shutdown(Int32 exitCode)
   at System.Application.UI.Program.<Main>g__HandleGlobalException|6_5(Exception ex, String name, Nullable`1 isTerminating)
```

**Comment by rmbadmin** [comment]
> @rmbadmin
> 
> Image2 引发了 空指针异常
> 
> ```
> 2021-05-02 21:05:49.7154|Error|Main|Stopped program because of exception, name: Main, isTerminating:  | System.NullReferenceException: Arg_NullReferenceException
>    at Avalonia.Skia.ImmutableBitmap..ctor(Stream stream, Int32 decodeSize, Boolean horizontal, BitmapInterpolationMode interpolationMode) in /_/src/Skia/Avalonia.Skia/ImmutableBitmap.cs:line 62
>    at Avalonia.Skia.PlatformRenderInterface.LoadBitmapToWidth(Stream stream, Int32 width, BitmapInterpolationMode interpolationMode) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 89
>    at Avalonia.Media.Imaging.Bitmap.DecodeToWidth(Stream stream, Int32 width, BitmapInterpolationMode interpolationMode) in /_/src/Avalonia.Visuals/Media/Imaging/Bitmap.cs:line 24
>    at AvaloniaGif.Image2.<SourceChanged>g__DecodeImage|44_0(Stream stream, <>c__DisplayClass44_0& )
>    at AvaloniaGif.Image2.SourceChanged(AvaloniaPropertyChangedEventArgs e)
> ```
> 
> API 的 SSL 证书验证失败，很奇怪
> 
> ```
> 2021-05-03 14:20:20.8285|Error|CloudServiceClient|ApiConn Fail(1006)，Url：api/Accelerate/All | System.Net.Http.HttpRequestException: net_http_ssl_connection_failed
>  ---> System.Security.Authentication.AuthenticationException: net_ssl_io_cert_validation, RemoteCertificateNameMismatch, RemoteCertificateChainErrors
>    at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
> ```
> 
> DNS 解析问题？这个错误重复次数巨多
> 
> ```
> 2021-05-03 23:30:53.6190|Error|Proxy|ProxyServer ExceptionFunc | System.Exception: Exception thrown in user event
>  ---> System.Net.Sockets.SocketException (11001): 不知道这样的主机。
>    at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
>    at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped)
> Exception_EndStackTraceFromPreviousThrow
>    at System.Application.Services.Implementation.HttpProxyServiceImpl.OnRequest(Object sender, SessionEventArgs e)
>    at Titanium.Web.Proxy.Extensions.FuncExtensions.internalInvokeAsync[T](AsyncEventHandler`1 callback, Object sender, T args, ExceptionHandler exceptionFunc)
>    Exception_EndOfInnerExceptionStack
> ```
> 
> 代理域名的证书与源网站证书算法不一致？
> 
> ```
> 2021-05-04 07:58:37.4060|Error|Proxy|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'discord.com' with certificate 'discord.com'.
>  ---> System.Security.Authentication.AuthenticationException: net_auth_SSPI
>  ---> System.ComponentModel.Win32Exception (0x80090331): 因为算法不同，客户端和服务器无法通信。
>    Exception_EndOfInnerExceptionStack
>    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
>    at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
>    Exception_EndOfInnerExceptionStack
>    at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
> ```
> 
> OOM
> 
> ```
> 2021-05-04 15:04:24.9837|Error|SteamConnectService|Task LongRunning | System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
> ```
> 
> App.Shutdown 没在主线程中执行
> 
> ```
> 2021-05-04 15:04:25.4429|Error|Main|(App)Close exception when exception occurs | System.InvalidOperationException: Call from invalid thread
>    at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
>    at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 701
>    at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 523
>    at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 491
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 88
>    at System.Application.UI.App.Shutdown(Int32 exitCode)
>    at System.Application.UI.Program.<Main>g__HandleGlobalException|6_5(Exception ex, String name, Nullable`1 isTerminating)
> 2021-05-04 15:04:25.6160|Error|Main|Stopped program because of exception, name: UnhandledException, isTerminating: True | System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
>    at System.Threading.Thread.StartCallback()
> 2021-05-04 15:04:25.6308|Error|Main|(App)Close exception when exception occurs | System.InvalidOperationException: Call from invalid thread
>    at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
>    at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 701
>    at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 523
>    at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 491
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 88
>    at System.Application.UI.App.Shutdown(Int32 exitCode)
>    at System.Application.UI.Program.<Main>g__HandleGlobalException|6_5(Exception ex, String name, Nullable`1 isTerminating)
> 2021-05-04 15:04:25.7245|Error|Main|Stopped program because of exception, name: UnhandledException, isTerminating: True | System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
>    at System.Threading.Thread.StartCallback()
> 2021-05-04 15:04:25.7245|Error|Main|(App)Close exception when exception occurs | System.InvalidOperationException: Call from invalid thread
>    at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
>    at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 701
>    at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 523
>    at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 491
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 88
>    at System.Application.UI.App.Shutdown(Int32 exitCode)
>    at System.Application.UI.Program.<Main>g__HandleGlobalException|6_5(Exception ex, String name, Nullable`1 isTerminating)
> 2021-05-04 15:04:25.8499|Error|Main|Stopped program because of exception, name: UnhandledException, isTerminating: True | System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
>    at System.Threading.Thread.StartCallback()
> 2021-05-04 15:04:25.8654|Error|Main|(App)Close exception when exception occurs | System.InvalidOperationException: Call from invalid thread
>    at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
>    at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 701
>    at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 523
>    at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 491
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 88
>    at System.Application.UI.App.Shutdown(Int32 exitCode)
>    at System.Application.UI.Program.<Main>g__HandleGlobalException|6_5(Exception ex, String name, Nullable`1 isTerminating)
> ```

Image2 的空指针是已经修复了的，
其它问题也已经修复
