### ISSUE TITLE
🧐[Question] 单独提取的 SNI bypass

### ISSUE THREAD

**Issue by F-TD5X** [SteamTools-Team/SteamTools#244]
### 🧐 问题描述(Description)

由于主要使用Linux，对于被 SNI 阻断的网站想使用该项目部分代码来bypass。

从原代码中去除了关于脚本和windows系统代理的部分。

以下是修改后的代码，在`Titanium.Web.Proxy`没有对应的issue，且该项目不怎么活跃，所以来这里问问有没有什么看法。

<details>
<summary>HttpProxy.cs</summary>

```C#

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Titanium.Web.Proxy;
using Titanium.Web.Proxy.EventArguments;
using Titanium.Web.Proxy.Http;
using Titanium.Web.Proxy.Models;

namespace Proxy
{
    public class HttpProxy : IDisposable
    {

        private IReadOnlyCollection<ProxyDomainModel> ProxyDomains;
        private readonly ProxyServer proxyServer = new ProxyServer();
        private string CertificateName { get; }
        public bool ProxyRunning => proxyServer.ProxyRunning;

        public HttpProxy(IReadOnlyCollection<ProxyDomainModel> proxyDomains, string certificateName)
        {
            ProxyDomains = proxyDomains;
            CertificateName = certificateName;
            proxyServer.ThreadPoolWorkerThread = Environment.ProcessorCount;
            proxyServer.CertificateManager.PfxFilePath = Path.Combine(AppContext.BaseDirectory, $@"{CertificateName}.Certificate.pfx");
            proxyServer.CertificateManager.RootCertificateIssuerName = $"{CertificateName} Certificate Authority";
            proxyServer.CertificateManager.RootCertificateName = $"{CertificateName} Certificate";
            // proxyServer.CertificateManager.CertificateEngine = Titanium.Web.Proxy.Network.CertificateEngine.BouncyCastleFast;
        }

        public bool Startup()
        {
            if(!IsCertificateInstalled(proxyServer.CertificateManager.RootCertificate)){
                if(!SetupCertificate()) return false;
            }
            if(PortInUse(443)) return false;

            proxyServer.BeforeRequest += OnRequest;
            proxyServer.BeforeResponse += OnResponse;
            try{
                DeleteHosts();
                SetupHosts();
            }catch(Exception ex){
                ;
            }

            proxyServer.AddEndPoint(new TransparentProxyEndPoint(IPAddress.Any,443,true){});
            proxyServer.AddEndPoint(new TransparentProxyEndPoint(IPAddress.Any,80,false));

            proxyServer.ExceptionFunc = ((Exception ex)=> {
                Console.Error.WriteLine(ex);
            });

            try{
                proxyServer.Start();
            }catch(Exception ex){
                Console.Error.WriteLine(ex);
                return false;
            }
            foreach (var endPoint in proxyServer.ProxyEndPoints)
                Console.WriteLine("Listening on '{0}' endpoint at Ip {1} and port: {2} ",
                    endPoint.GetType().Name, endPoint.IpAddress, endPoint.Port);

            return true;
        }
        public void Stop()
        {
            if(proxyServer.ProxyRunning){
                proxyServer.BeforeRequest -= OnRequest;
                proxyServer.BeforeResponse -= OnResponse;
                proxyServer.Stop();
                DeleteHosts();
            }
        }

        public void Dispose()
        {
            if (proxyServer.ProxyRunning)
            {
                proxyServer.Stop();
                DeleteHosts();
            }
            proxyServer.Dispose();
        }

        public bool IsCertificateInstalled(X509Certificate2 certificate2)
        {
            if (certificate2 == null)
                return false;
            using var store = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
            store.Open(OpenFlags.MaxAllowed);
            return store.Certificates.Contains(certificate2);
        }
        private bool SetupCertificate()
        {
            if (!proxyServer.CertificateManager.CreateRootCertificate(true))
            {
                Console.Error.Write("Can't create root certificate");
                return false;
            }
            proxyServer.CertificateManager.RootCertificate.SaveCerCertificateFile(Path.Combine(AppContext.BaseDirectory, $@"{CertificateName}.Certificate.cer"));
            proxyServer.CertificateManager.EnsureRootCertificate();
            return IsCertificateInstalled(proxyServer.CertificateManager.RootCertificate);
        }
        public static bool PortInUse(int port)
        {
            var ipProperties = System.Net.NetworkInformation.IPGlobalProperties.GetIPGlobalProperties();
            IPEndPoint[] iPEndPoints = ipProperties.GetActiveTcpListeners();
            foreach (IPEndPoint endPoint in iPEndPoints)
            {
                if (endPoint.Port == port)
                    return true;
            }
            return false;
        }
        public async Task OnRequest(object sender, SessionEventArgs e){
            Console.WriteLine($"Receiving: {e.HttpClient.Request.RequestUri.AbsoluteUri}");
            foreach(var item in ProxyDomains){
                if(!item.IsEnable) continue;
                foreach(var host in item.Domains){
                    if(e.HttpClient.Request.RequestUri.AbsoluteUri.Contains(host)){
                        if(e.HttpClient.Request.RequestUri.Scheme.Equals("http",StringComparison.OrdinalIgnoreCase)){
                            e.Redirect(e.HttpClient.Request.RequestUri.AbsoluteUri.Remove(0, 4).Insert(0, "https"));
                            Console.WriteLine($"Redirecting: {e.HttpClient.Request.RequestUri.AbsoluteUri}");
                            return;
                        }
                        if(item.IsRedirect){
                            e.Redirect(e.HttpClient.Request.RequestUri.AbsoluteUri.Replace(e.HttpClient.Request.RequestUri.Host, item.ToDomain));
                            return;
                        }
                        
                        IPAddress iP = null;
                        if(!string.IsNullOrEmpty(item.ProxyIPAddres)) iP = IPAddress.Parse(item.ProxyIPAddres);
                        else{
                            var iPs = await Dns.GetHostAddressesAsync(item.ToDomain);
                            iP = iPs.FirstOrDefault();
                        }
                        if(iP!= null){
                            e.HttpClient.UpStreamEndPoint = new IPEndPoint(IPAddress.Parse(iP.ToString()),item.Port);
                            Console.WriteLine($"Proxy to IP: {IPAddress.Parse(iP.ToString())}");
                        }
                        if (e.HttpClient.ConnectRequest?.ClientHelloInfo != null)
                        {
                            Console.WriteLine($"ClientHelloInfo Info:  {e.HttpClient.ConnectRequest.ClientHelloInfo}");
                            if (!string.IsNullOrEmpty(item.ServerName))
                            {
                                var sni = e.HttpClient.ConnectRequest.ClientHelloInfo.Extensions["server_name"];
                                e.HttpClient.ConnectRequest.ClientHelloInfo.Extensions["server_name"] =
                                    new Titanium.Web.Proxy.StreamExtended.Models.SslExtension(sni.Value, sni.Name, item.ServerName, sni.Position);
                            }
                            else
                            {
                                e.HttpClient.ConnectRequest.ClientHelloInfo.Extensions.Remove("server_name");
                            }
                        }
                        
                        return;
                    }
                }
            }
            
            await Dns.GetHostAddressesAsync(e.HttpClient.Request.Host).ContinueWith(s => {
                if(IPAddress.IsLoopback(s.Result.FirstOrDefault())
                || ProxyDomains.Count(w => w.IsEnable && w.Hosts.Contains(e.HttpClient.Request.Host)) == 0
                ){
                    e.Ok($"URL : {e.HttpClient.Request.RequestUri.AbsoluteUri} \r\n not support proxy");
                    return;
                }
                Console.WriteLine($"IsLoopback OnRequest: {e.HttpClient.Request.RequestUri.AbsoluteUri}");
            });
            e.Ok($"URL : {e.HttpClient.Request.RequestUri.AbsoluteUri} {Environment.NewLine}not support proxy");
            return ;
        }
        public async Task OnResponse(object sender,SessionEventArgs e){}
        public void SetupHosts()
        {
            var OSInfo = Environment.OSVersion;
            string pathpart = "hosts";
            if (OSInfo.Platform == PlatformID.Win32NT)
            {
                pathpart = "system32\\drivers\\etc\\hosts";
            }
            string hostfile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), pathpart);
            List<string> lines = new List<string>();
            lines.Add("# Sibalaxi");
            foreach (var proxyDomains in ProxyDomains)
            {
                Console.Out.WriteLine(String.Format("{0} is {1}", proxyDomains.Hosts.First(), proxyDomains.IsEnable));
                if (proxyDomains.IsEnable)
                {
                    foreach (var host in proxyDomains.Hosts)
                    {
                        if (host.Contains(" "))
                        {
                            var h = host.Split(' ');
                            lines.Add(String.Format("{0} {1}", h[0], h[1]));
                        }
                        else
                            lines.Add(String.Format("{0} {1}", IPAddress.Loopback.ToString(), host));
                    }
                }
            }
            lines.Add("# Sibalaxi");

            if (!File.ReadAllLines(hostfile).Contains("# Sibalaxi"))
            {
                try
                {
                    File.AppendAllLines(hostfile, lines);
                }
                catch (Exception ex)
                {
                    Console.Error.Write(ex);
                }
            }
        }
        public void DeleteHosts()
        {
            var OSInfo = Environment.OSVersion;
            string pathpart = "hosts";
            if (OSInfo.Platform == PlatformID.Win32NT)
            {
                //is windows NT
                pathpart = "system32\\drivers\\etc\\hosts";
            }
            string hostfile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), pathpart);
            List<string> lines = new List<string>(File.ReadAllLines(hostfile));
            var index = lines.Select((x, i) => new { x, i })
                             .Where(x => x.x == "# Sibalaxi")
                             .Select(x => x.i).ToList();
            if (index.Count() != 2)
            {
                return;
            }
            else
            {
                lines.RemoveRange(index[0], index[1] - index[0] + 1);
            }
            File.WriteAllLines(hostfile, lines);
        }
    }
}
```

</details>

### 🚑 其他信息(Other Information)

目前只使用了 https://github.com/SteamTools-Team/SteamTools/blob/28f1198a9cb2292ae5ec05a89cb60c21db66590d/source/SteamTool.Proxy/HttpProxy.cs 里的代码，但遇到如下错误：
<details>
<summary>exception</summary>

```
Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request
 ---> System.Exception: Could not establish connection to raw.github.com
 ---> System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.createServerConnection(String remoteHostName, Int32 remotePort, Version httpVersion, Boolean isHttps, SslProtocols sslProtocol, List`1 applicationProtocols, Boolean isConnect, ProxyServer proxyServer, SessionEventArgsBase sessionArgs, IPEndPoint upStreamEndPoint, IExternalProxy externalProxy, String cacheKey, Boolean prefetch, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   --- End of inner exception stack trace ---
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleHttpSessionRequest(ProxyEndPoint endPoint, HttpClientStream clientStream, CancellationTokenSource cancellationTokenSource, TunnelConnectSessionEventArgs connectArgs, Task`1 prefetchConnectionTask, Boolean isHttps)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
```

</details>

**Comment by AigioL** [comment]
```System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.```
这个异常 在 https://docs.microsoft.com/zh-cn/windows/win32/winsock/windows-sockets-error-codes-2 上有详细的描述



WSAEADDRNOTAVAIL 10049 | 无法分配请求的地址。请求的地址在其上下文中无效。 这通常是由于尝试&nbsp;绑定&nbsp;到本地计算机无效的地址而导致的。 当远程地址或端口对于远程计算机 (（例如，地址或端口 0) ）无效时，这也可能是由于&nbsp;连接、&nbsp;sendto、&nbsp;WSAConnect、&nbsp;WSAJoinLeaf或&nbsp;WSASendTo&nbsp;导致的。
-- | --




可能与防火墙有关？

或者用 V2 版本的实现
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client/Services/Implementation/HttpProxyServiceImpl.cs

**Comment by F-TD5X** [comment]
弃了弃了，同样的问题，搞不清楚，还是 caddy 好用。
