### ISSUE TITLE
🐛[BUG] 使用中突然崩溃

### ISSUE THREAD

**Issue by yanxiatao** [SteamTools-Team/SteamTools#266]
### 🐛 描述(Description)
 

使用中突然报错，然后停止运行

### 📷 复现步骤(Steps to Reproduce)

无

### 📄 [异常/日志]信息([Exception/Log] Information)
2021-05-27 19:09:03.3804|Error|Proxy|ProxyServer ExceptionFunc | System.Exception: Error occured in whilst handling the client
 ---> System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
   at System.Number.Int32ToHexStr(Int32 value, Char hexBase, Int32 digits)
   at System.Number.<FormatUInt32>g__FormatUInt32Slow|40_0(UInt32 value, String format, IFormatProvider provider)
   at Titanium.Web.Proxy.StreamExtended.SslExtensions.<>c.<ByteArrayToString>b__7_0(Byte x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Titanium.Web.Proxy.StreamExtended.SslExtensions.ByteArrayToString(Byte[] data)
   at Titanium.Web.Proxy.StreamExtended.SslExtensions.GetExtensionData(Int32 value, Byte[] data)
   at Titanium.Web.Proxy.StreamExtended.SslExtensions.GetExtension(Int32 value, Byte[] data, Int32 position)
   at Titanium.Web.Proxy.StreamExtended.SslTools.ReadExtensions(Int32 majorVersion, Int32 minorVersion, PeekStreamReader peekStreamReader, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.StreamExtended.SslTools.PeekClientHello(IPeekStream clientStream, IBufferPool bufferPool, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
2021-05-27 19:09:23.4521|Error|Proxy|ProxyServer ExceptionFunc | System.Exception: Error occured in whilst handling the client
 ---> System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
   at Titanium.Web.Proxy.StreamExtended.BufferPool.DefaultBufferPool.GetBuffer()
   at Titanium.Web.Proxy.Extensions.StreamExtensions.CopyToAsync(Stream input, Stream output, Action`3 onCopy, IBufferPool bufferPool, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Helpers.TcpHelper.sendRawTap(Stream clientStream, Stream serverStream, IBufferPool bufferPool, Action`3 onDataSend, Action`3 onDataReceive, CancellationTokenSource cancellationTokenSource)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
2021-05-27 19:09:28.8619|Error|Proxy|ProxyServer ExceptionFunc | System.Exception: An error occurred when disposing server connections.
 ---> System.Threading.Tasks.TaskSchedulerException: TaskSchedulerException_ctor_DefaultMessage
 ---> System.OutOfMemoryException: Exception_WasThrown, System.OutOfMemoryException
   at System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPush(Object obj)
   at System.Threading.ThreadPoolWorkQueue.Enqueue(Object callback, Boolean forceGlobal)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   Exception_EndOfInnerExceptionStack
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task`1.StartNew(Task parent, Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler)
   at System.Threading.Tasks.Task.Run(Func`1 function, CancellationToken cancellationToken)
   at Titanium.Web.Proxy.Network.Tcp.TcpServerConnection.Dispose(Boolean disposing)
   at Titanium.Web.Proxy.Network.Tcp.TcpConnectionFactory.clearOutdatedConnections()
   Exception_EndOfInnerExceptionStack
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):  v2.3.0
- 系统版本号(OS Version):  Windows 专业工作站版 20H2（19042.985）

### 🖼 截图(Screenshots)

暂无

**Comment by AigioL** [comment]
关于OOM的问题，目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
