### ISSUE TITLE
社区加速无法加速

### ISSUE THREAD

**Issue by zc16399** [SteamTools-Team/SteamTools#269]
2021-05-31 19:08:23.4482|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

**Comment by zc16399** [comment]
![Uploading image.png…]()

**Comment by zc16399** [comment]
![image](https://user-images.githubusercontent.com/45933389/120185432-b9080b00-c201-11eb-858b-903169dc9037.png)

**Comment by rmbadmin** [comment]
2.4.1应该已经修复
