### ISSUE TITLE
🐛[BUG] 社区加速功能导致上网问题

### ISSUE THREAD

**Issue by moeshin** [SteamTools-Team/SteamTools#291]
### 🐛 描述(Description)

电脑经常是长期开着的，wifi 热点 + UU 加速 + Trojan + 本软件的社区加速功能（HOSTS 代理模式），经常一天后多次出现会网络问题。

任何网页要超多次请求才能显示，Chrome 报 `ERR_CONNECTION_FAILED`，CURL 报 `curl: (6) getaddrinfo() thread failed to start`。

对上面软件逐个关闭，发现问题出在本软件上，即使关闭社区加速功能，问题依旧存在，需要退出软件。

刚更新到 2.4.1，先插个眼，过几天再看看。

### 📄 [异常/日志]信息([Exception/Log] Information)

日志中多次出现 `由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。`，但我内存硬盘剩余空间都足够大。

#287 好像类似

```text
2021-06-21 17:02:41.1671|Error|Proxy|StartProxy | System.Net.Sockets.SocketException (10055): 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at System.Application.Services.Implementation.HttpProxyServiceImpl.GetRandomUnusedPort()
   at System.Application.Services.Implementation.HttpProxyServiceImpl.StartProxy(Boolean IsWindowsProxy, Boolean IsProxyGOG)
2021-06-21 17:02:45.3743|Error|CloudServiceClient|ApiConn Fail(1006)，Url：api/script/updates | System.Net.Http.HttpRequestException: 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。 (api.steampp.net:443)
 ---> System.Net.Sockets.SocketException (10055): 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|271_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Application.Services.CloudService.ApiConnection.SendCoreAsync[TRequestModel,TResponseModel](Boolean isAnonymous, Boolean isApi, CancellationToken cancellationToken, HttpMethod method, String requestUri, TRequestModel requestModel, Boolean responseContentMaybeNull, Boolean isSecurity, Boolean isShowResponseErrorMessage, String errorAppendText)
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.3.0
- 系统版本号(OS Version): 
  > 版本	Windows 10 专业工作站版
  > 版本号	20H2
  > 安装日期	‎2020/‎11/‎3
  > 操作系统内部版本	19042.1052
  > 体验	Windows Feature Experience Pack 120.2212.2020.0

**Comment by rmbadmin** [comment]
2.4.1应该是已经修复了，可以在测试一段时间，如问题依然存在麻烦再次反馈一下 谢谢。

**Comment by moeshin** [comment]
新版本问题依旧，更新完半天还是有问题。

![屏幕截图(9)](https://user-images.githubusercontent.com/28248888/122797671-4d8df680-d2f2-11eb-87dd-42d54930440d.png)

**Comment by moeshin** [comment]
> 这个错误可能是你计算机的 Socket 句柄资源用尽导致的，能够造成这种现象的一种情况就是你的计算机的某个程序不断的向某个连接发出连接申请，但是始终没能连上，没连上就会引发一个错误，如果软件编程的人没有写释放资源的代码，那么这个连接就始终占据着着一个句柄，于是由于不断的连接，最终导致 Socket 句柄资源耗尽。

**Comment by moeshin** [comment]
#287 相同问题
