### ISSUE TITLE
🐛[BUG]  客户端错误1006

### ISSUE THREAD

**Issue by buiawpkgew1** [SteamTools-Team/SteamTools#709]
![image](https://user-images.githubusercontent.com/71136405/143734058-ff08d406-fa58-4b65-bc1d-57921600b11e.png)

**Comment by buiawpkgew1** [comment]
这个怎么回事？

**Comment by AigioL** [comment]
在日志中有 ApiConn Fail 的内容吗？日志可以在 ```设置 - 通用设置 - 存储空间 - 打开Logs文件夹``` 中查看

**Comment by buiawpkgew1** [comment]
> 在日志中有 ApiConn Fail 的内容吗？日志可以在 `设置 - 通用设置 - 存储空间 - 打开Logs文件夹` 中查看

![image](https://user-images.githubusercontent.com/71136405/144588422-8ccaf087-dbb1-47d3-982b-c068925cba40.png)

**Comment by rmbadmin** [comment]
> > 在日志中有 ApiConn Fail 的内容吗？日志可以在 `设置 - 通用设置 - 存储空间 - 打开Logs文件夹` 中查看
> 
> ![image](https://user-images.githubusercontent.com/71136405/144588422-8ccaf087-dbb1-47d3-982b-c068925cba40.png)

这是appdata文件夹不是logs文件夹

**Comment by buiawpkgew1** [comment]
[nlog-all-2021-11-21.log](https://github.com/SteamTools-Team/SteamTools/files/7648800/nlog-all-2021-11-21.log)

**Comment by buiawpkgew1** [comment]
[nlog-all-2021-11-28.log](https://github.com/SteamTools-Team/SteamTools/files/7648912/nlog-all-2021-11-28.log)

**Comment by AigioL** [comment]
根据日志来看目前所有 Http 请求都产生了这个异常，目前使用的 Http2 与 TLS1.3 可能在你的机器上不支持，你的系统操作版本号是多少？

```
2021-11-28 13:20:33.4510|Error|CloudServiceClient|ApiConn Fail(1006)，Url：api/Accelerate/All | System.Net.Http.HttpRequestException: net_http_ssl_connection_failed
 ---> System.Security.Authentication.AuthenticationException: net_auth_SSPI
 ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持
   Exception_EndOfInnerExceptionStack
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Application.Services.CloudService.ApiConnection.SendCoreAsync[TRequestModel,TResponseModel](Boolean isAnonymous, Boolean isApi, CancellationToken cancellationToken, HttpMethod method, String requestUri, TRequestModel requestModel, Boolean responseContentMaybeNull, Boolean isSecurity, Boolean isShowResponseErrorMessage, String errorAppendText)
```

**Comment by buiawpkgew1** [comment]
> 根据日志来看目前所有 Http 请求都产生了这个异常，目前使用的 TLS1.2 可能在你的机器上不支持，你的系统操作版本号是多少？
> 
> ```
> 2021-11-28 13:20:33.4510|Error|CloudServiceClient|ApiConn Fail(1006)，Url：api/Accelerate/All | System.Net.Http.HttpRequestException: net_http_ssl_connection_failed
>  ---> System.Security.Authentication.AuthenticationException: net_auth_SSPI
>  ---> System.ComponentModel.Win32Exception (0x80090302): 要求的函数不受支持
>    Exception_EndOfInnerExceptionStack
>    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
>    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
>    Exception_EndOfInnerExceptionStack
>    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
>    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at System.Application.Services.CloudService.ApiConnection.SendCoreAsync[TRequestModel,TResponseModel](Boolean isAnonymous, Boolean isApi, CancellationToken cancellationToken, HttpMethod method, String requestUri, TRequestModel requestModel, Boolean responseContentMaybeNull, Boolean isSecurity, Boolean isShowResponseErrorMessage, String errorAppendText)
> ```
> 
> 抛出异常的源码在 https://github.com/dotnet/runtime/blob/v6.0.0/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L364
> 
> Windows TLS 协议版本支持 https://docs.microsoft.com/zh-cn/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support

版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎10/‎22
操作系统内部版本	19044.1466
体验	Windows Feature Experience Pack 120.2212.3920.0

**Comment by buiawpkgew1** [comment]
我还是不能用
